import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'サイトマップ | US ESTA Apply Website',
  description: '当サイト内の各ページへのリンクをカテゴリー別に整理した一覧ページです。目的の情報へスムーズにアクセスいただけます。',
};

const BODY_HTML = `<section class="article-hero"><div class="article-hero__inner"><nav class="crumb"><a href="/">HOME</a><span>›</span><em>サイトマップ</em></nav><p class="article__eyebrow">Sitemap</p><h1 class="article__title">サイトマップ</h1><p class="article__lede">当サイト内の各ページへのリンクをカテゴリー別に整理しています。目的の情報へスムーズにアクセスいただけます。</p></div></section><section class="article-main"><div class="article-main__inner article-main__inner--no-toc"><article class="article-body"><section class="fade-up"><h3><a href="/list-esta-application">ESTA申請関連情報</a></h3><ul><li><a href="/">TOPページ</a></li><li><a href="/list-esta-application/esta">ESTA(エスタ)とは？事前入国審査制度を解説</a></li><li><a href="/list-esta-application/esta-flow">【記入例付き】ESTAの申請方法を解説</a></li><li><a href="/list-esta-application/place-of-birth">出生地や住所の書き方を紹介</a></li><li><a href="/list-esta-application/us-contact-details">米国内の連絡先情報の記入方法</a></li><li><a href="/list-esta-application/fee">ESTAの申請料金</a></li><li><a href="/list-esta-application/expiration-date">ESTAの有効期限と再申請・確認方法</a></li><li><a href="/list-esta-application/official-cbp">公式ウェブサイトについて解説</a></li><li><a href="/list-esta-application/cbp-flow">ESTA申請方法と取得手順を徹底解説</a></li><li><a href="/list-esta-application/application">アプリのESTA申請方法</a></li><li><a href="/list-esta-application/status-check">ESTA申請状況の確認方法</a></li><li><a href="/list-esta-application/guam">グアム入国にESTAは必要？</a></li></ul></section><section class="fade-up"><h3><a href="/list-site-information">サイト情報</a></h3><ul><li><a href="/list-site-information/entry">申請書記入</a></li><li><a href="/list-site-information/status">申請状況確認</a></li><li><a href="/list-site-information/contact">お問い合わせ</a></li><li><a href="/list-site-information/privacy-policy">個人情報保護方針</a></li><li><a href="/list-site-information/aboutus">特定商取引法に基づく表記・運営者情報</a></li><li><a href="/list-site-information/contents-policy">コンテンツポリシー</a></li><li><a href="/list-site-information/agreement">利用規約</a></li><li><a href="/list-site-information/browser">推奨ブラウザ</a></li></ul></section></article></div></section><section class="cta-strip cta-strip--solid"><p class="cta-strip__eyebrow">Start your application</p><h2>アメリカ渡航には<br class="sp-br"/>ESTAの申請が必要です。</h2><p>申請完了まで最大3日ほどかかるため、<br class="sp-br"/>余裕をもってお手続きください。</p><a class="cta-btn" href="/list-site-information/entry">✓ ESTA申請をはじめる</a></section>`;

export default function Page() {
  return <div className="redesign-detail" dangerouslySetInnerHTML={{ __html: BODY_HTML }} />;
}
